language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sebslon/docker-travis-aws-cicd -f Dockerfile.dev .

script:
  - docker run -e CI=true sebslon/docker-travis-aws-cicd npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "travis-docker-react"
  env: "Travisdockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-665598615361"
  bucket_path: "travis-docker-react"
  on:
    branch: main
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
