FROM node:16-alpine

WORKDIR '/app'

COPY package.json .

RUN npm install

# Set up reference to local env for hot reloading - volume command (-v) 
# BOOKMARKING VOLUMES
## docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app <image_id> ##

COPY . .

CMD ["npm", "run", "start"]